ARG  IMG_BASE
ARG  CODE_VERSION=latest
FROM ${IMG_BASE}:${CODE_VERSION}

LABEL maintainer="Louis T. Getterman IV <Thad.Getterman@gmail.com>"
LABEL "org.getterman.thad.vendor"="Louis T. Getterman IV"

WORKDIR /usr/src/app

#----------------------------------------------------------------------- DEVELOP

# Docker Setup
COPY	./docker/setup/ /tmp/setup/

# Application Setup
COPY	./app/.dbt/setup/ /usr/src/app/.dbt/setup/

# Docker Setup -> Application Setup
RUN		/tmp/setup/main.bash

# Application
COPY	./app/ /usr/src/app/

#-----------------------------------------------------------------------/DEVELOP

CMD	[ "/bin/bash", "/usr/src/app/launch.bash" ]
