ARG  IMG_BASE
ARG  CODE_VERSION=latest
FROM ${IMG_BASE}:${CODE_VERSION}

LABEL maintainer="Louis T. Getterman IV <Thad.Getterman@gmail.com>"
LABEL "org.getterman.thad.vendor"="Louis T. Getterman IV"

WORKDIR /usr/src/app

#----------------------------------------------------------------------- DEVELOP

COPY	./docker/setup/ /tmp/setup/
COPY	./app/setup/ /usr/src/app/setup/

RUN		/tmp/setup/main.bash

COPY	./app/ /usr/src/app/

#-----------------------------------------------------------------------/DEVELOP

CMD	[ "/bin/bash", "/usr/src/app/launch.bash" ]
